name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.iog.io https://cache.nixos.org
    - uses: cachix/cachix-action@v12
      with:
        name: tweag-webauthn
        authToken: '${{ secrets.CACHIX_TWEAG_WEBAUTHN_AUTH_TOKEN }}'

    - name: "Nix build"
      run: nix build -L .#webauthn:lib:webauthn .#server:exe:server

  dev:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.iog.io https://cache.nixos.org
    - uses: cachix/cachix-action@v12
      with:
        name: tweag-webauthn
        authToken: '${{ secrets.CACHIX_TWEAG_WEBAUTHN_AUTH_TOKEN }}'

    - name: "Nix shell"
      run: nix develop --command echo Success

    - name: "Cabal build and test"
      run: nix develop --command cabal run test:tests

    - name: "Style check"
      run: nix develop --command bin/format-check.sh
